In [15]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [43]:
df=pd.read_csv('homeprices (2).csv')
df
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [ ]:
FOR EXAMPLE IN THE ABOVE DATASET THERE ARE 3 TOWNS MONROE TOWNSHIP, WEST WINDSOR AND ROBINSVILLE EACH WITH ITS¶
OWN SET OF PRICE ACCORDING AREA
NOW SINCE COMPUTER DOESNT UNDERSTAND TEXTUAL DATA WE CAN USE NUMERICAL DATA LIKE 1,2,3
BUT NUMBERING THE TOWNS AS 1,2,3 CAN CAUSE CONFUSION FOR THE MACHINE LEARNING MODEL SINCE IT WILL ASSUME
ROBINSVILLE > WEST WINDSOR > MONROE AS IT IS 3>2>1
THESE COME UNDER CATEGORICAL VALUES WHEREIN THERE ARE 2 TYPES NAMELY
1) NOMINAL VALUE - WHERE ALL THE GROUPS ARE ON AN EQUAL LEVEL AND ONE GROUP IS NOT SUPERIOR OVER OTHER LIKE COLOURS
RED , GREEN, VALUE OR TOWNSHIPS - BESANT NAGAR, ADYAR, GUINDY
2) ORDINAL VALUE - WHERE ALL THE GROUPS ARE IN COMPETITIVE ORDER LIKE AND GROUP IS SUPERIOR OVER OTHER LIKE HIGH,
MEDIUM, LOW ... GOOD,BAD AND UGLY OR SATISFIED, NEUTRAL AND DISATISFIED

In [5]:
dummies=pd.get_dummies(df.town,dtype=int)
dummies

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [6]:
merged=pd.concat([df,dummies],axis='columns')
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [12]:
merged.columns

Index(['town', 'area', 'price', 'monroe township', 'robinsville',
       'west windsor'],
      dtype='object')

In [7]:
# DUMMY VARIABLE TRAP 
# WHENEVER ONE VARIABLE CAN BE REPRESENTED BY ANOTHER IT CALLED MULTI-COLINEAR AND WHENEVER YOU HAVE MULTI-COLINEAR
# VARIABLE IT CREATES THE DUMMY VARIABLE TRAP 
# SO WE CAN DELETE ONE COLUMN OF THE DUMMY VARIABLE AS 2 COLUMNS IS ENOUGH THE OTHER 1 COLUMN CAN BE REPRESENTED AS 
# THE OPPOSITE/NEGATIVE OF THE 2 
# FOR EXAMPLE WHEN BOTH THE COLUMNS MONROE TOWNSHIP AND ROBINSVILLE HAS 0 AS THE VALUE FOR A ROW THEN IT MEANS IT IS
# WEST WINDSOR
# THE SKLEARN LINEAR REGRESSION WILL AUTOMATICALLY DROP THE MULTI-COLINEAR COLUMN VARIABLE BUT IT IS GOOD PRACTICE
# TO DROP THE COLUMN MANUALLY

In [14]:
final_df=merged.drop(['town','west windsor'], axis='columns')
final_df

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [19]:
# LETS CREATE A SEPERATE OBJECT FOR THE INPUT DATAFRAME
X = final_df.drop(['price'], axis='columns')
X

area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [20]:
# LETS CREATE A SEPERATE OBJECT FOR PRICE 
Y = final_df.price
Y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [21]:
# WE ARE TRAINING THE LINEAR REGRESSION MODEL ON THE STORED OBJECTS
model=LinearRegression()
model.fit(X,Y)

LinearRegression()

In [24]:
# ASKING TO PREDICT 3550 SQT AREA PRICE IN MONROE TOWNSHIP
model.predict([[3550,1,0]])

C:\Users\Arjun VJ\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([660262.30918081])

In [25]:
# ASKING TO PREDICT 2000 SQT AREA PRICE WEST WINDSOR 
model.predict([[2000,0,0]])

C:\Users\Arjun VJ\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([503585.25048379])

In [44]:
# WE CAN DO THE SAME USING PREPROCESSING FUNCTION IN SKLEARN LIKE LABEL ENCODER AND ONEHOTENCODER
# WHERE THE LABEL ENCODER IS USED TO CREATE THE LABELS FOR THE DATAFRAME BASED ON SPECIFIC MENTIONED COLUMNS IN THE
# DATAFRAME
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
# USE fit_transform FUNCTION IN OF LabelEncoder TO TRANSFORM THE COLUMN INTO CATEGORICAL LABELS
df['town']=LE.fit_transform(df.town)
df

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [56]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [69]:
# NOW LETS CONVERT THE DATAFRAME INTO AN ARRAY 
X=df[['town','area']]
X

town  area
0      0  2600
1      0  3000
2      0  3200
3      0  3600
4      0  4000
5      2  2600
6      2  2800
7      2  3300
8      2  3600
9      1  2600
10     1  2900
11     1  3100
12     1  3600

In [70]:
Y = df.price
Y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [71]:
# OneHotEncoder()
# NOW TO ADD THE DUMMY VARIABLE COLUMN FROM THE LABELED COLUMNS WE USE ONEHOTENCODER
# SINCE WE DONT WANT THE ENTIRE X DATAFRAME TO BE CATEGORICALLY LABELLED AND WE ONLY WANT SPECIFIC COLUMNS
# WE USE COLUMN TRANSFORMER AND ONEHOTENCODER
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), ['town'])  # 'town' is the name of the column
    ],
    remainder='passthrough'  # Leave 'area' as-is
)

X=ct.fit_transform(X)
X

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [72]:
# TO AVOID DUMMY VARIABLE LETS DROP THE FIRST COLUMN 
X=X[:,1:] # THIS WILL SELECT ALL ROWS : AND 1: WILL CHOOSE COLUMNS AFTER 1ST COLUMNS
X

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [73]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X,Y)

LinearRegression()

In [74]:
# PREDICTS THE VALUE OF 3500 SQFT OF AREA OF MONROW TOWNSHIP AS IT IS 0,0 
model.predict([[0,0,3500]])

array([653917.4371103])