# K FOLD CROSS VALIDATION

In [58]:
# SO WE TRAIN IN THE MODEL IN 3 WAYS :- 
# 1) WHEREIN YOU TRAIN AND TEST THE MODEL WITH COMPLETE 100% OF THE DATASET BUT THIS CAN CAUSE OVERFITTING AS THE 
# MODEL WILL NOT LEARN AND IT IS NOT FAIR TO TEST THE MODEL ON THE SAME DATASET IT WAS TRAINED SINCE IT KNOWS THE 
# ANSWER
# 2) HERE WE SPLIT THE DATASET INTO TRAINING AND TESTING BUT THE DATASET MIGHT BE SPLIT IN SUCH A WAY THAT ONE 
# THE DATASET OF CATEGORY OF TARGET VARIABLE WAS TRAINED MORE AND THE OTHER LESS THIS CAN CAUSE FLUCTUATIONS IN THE
# PERFORMANCE OR ACCURACY OF THE MODEL AS EACH TIME IT IS TRAINED AND TESTED ON DIFFERENT DATASET
# 3) K FOLD - THIS IS WHERE WE TAKE THE DATASET AND SPLIT INTO FOLD AND A SET OF FOLDS ARE USED FOR TRAINING AND 
# REST FOR TESTING AND THIS IS DONE IN LOOP/ITERATION UNTIL ALL THE FOLDS ARE USED FOR TRAINING AND TESTING 
# THEN IN THE END THE AVERAGE SCORE/PERFORMANCE OF THE MODEL IS GIVEN AS THE PERFORMANCE OF THE MODEL
# THIS IS MORE FAIR SINCE THE MODEL IS TRAINED AND TESTED ACCROSS ALL THE DATASET AND ONLY THEN EVALUATED
# FOR EXAMPLE IF WE HAVE DATASET WITH 100 VALUES AND WE SPLIT IT INTO 5 FOLDS THEN :-
# 1ST ITERATION - THE 1ST FOLD IS RESERVED FOR TESTING AND 2-5 ARE USED FOR TRAINING 
# 2ND ITERATION - THE 2ND FOLD IS RESERVED FOR TESTING AND 1,3-5 ARE USED FOR TRAINING 
# 3RD ITERATION - THE 3RD FOLD IS RESERVED FOR TESTING AND 1-2,4-5 ARE USED FOR TRAINING 
# 4TH ITERATION - THE 4TH FOLD IS RESERVED FOR TESTING AND 1-3,5 ARE USED FOR TRAINING 
# 5TH ITERATION - THE 5TH FOLD IS RESERVED FOR TESTING AND 1-4 ARE USED FOR TRAINING 

In [59]:
import pandas as pd
import numpy as np 
from sklearn.datasets import load_digits

In [60]:
digits=load_digits()

In [61]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [62]:
#digits.feature_names

In [63]:
df=pd.DataFrame(digits.data)
df

0    1     2     3     4     5    6    7    8    9   ...   54   55  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  4.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  1.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  8.0  0.0   

       56   57   58    59    60    61   62   63  
0     0.0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1     0.0  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2     0.0  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3     0.0  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4     0.0  0.0  0.0   2.0  16.0   4.0  0.0  0.0  
...   ...  ...  ...   ...   ...   ...  ...  ...  
1792  0.0  0.0  2.0  14.0  15.0   9.0  0.0  0.0  
1793  0.0  0.0  6.0  16.0  14.0   6.0  0.0  0.0  
1794  0.0  0.0  2.0   9.0  13.0   6.0  0.0  0.0  
1795  0.0  0.0  5.0  12.0  16.0  12.0  0.0  0.0  
1796  0.0  1.0  8.0  12.0  14.0  12.0  1.0  0.0  

[1797 rows x 64 columns]

In [64]:
df['Target']=pd.DataFrame(digits.target)
df

0    1     2     3     4     5    6    7    8    9  ...   55   56  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  0.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  0.0  0.0   

       57   58    59    60    61   62   63  Target  
0     0.0  6.0  13.0  10.0   0.0  0.0  0.0       0  
1     0.0  0.0  11.0  16.0  10.0  0.0  0.0       1  
2     0.0  0.0   3.0  11.0  16.0  9.0  0.0       2  
3     0.0  7.0  13.0  13.0   9.0  0.0  0.0       3  
4     0.0  0.0   2.0  16.0   4.0  0.0  0.0       4  
...   ...  ...   ...   ...   ...  ...  ...     ...  
1792  0.0  2.0  14.0  15.0   9.0  0.0  0.0       9  
1793  0.0  6.0  16.0  14.0   6.0  0.0  0.0       0  
1794  0.0  2.0   9.0  13.0   6.0  0.0  0.0       8  
1795  0.0  5.0  12.0  16.0  12.0  0.0  0.0       9  
1796  1.0  8.0  12.0  14.0  12.0  1.0  0.0       8  

[1797 rows x 65 columns]

In [65]:
# LETS SPLIT THE DATASET INTO TRAINING AND TESTING TO TEST HOW THE MODEL'S PERFORMANCE FLUCTUATES WITH EACH TIME
# WE RUN THIS CELL AGAIN CAUSING THE ALTERING TRAINING AND TESTING DATASET
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(df.drop('Target',axis='columns'),df.Target,test_size=0.2)

In [66]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,Y_train)
model.score(X_test,Y_test)

C:\Users\Arjun VJ\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9527777777777777

In [67]:
from sklearn.svm import SVC
model=SVC()
model.fit(X_train,Y_train)
model.score(X_test,Y_test)

0.9805555555555555

In [68]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(X_train,Y_train)
model.score(X_test,Y_test)

0.975

In [69]:
# NOW LETS USE KFOLD FROM THE MODEL SELECTION MODULE OF SKLEARN
# n_splits PARAMETER DETERMINES THE NUMBER OF FOLDS KFOLD FUNCTION HAS TO PERFORM ON THE DATASET
from sklearn.model_selection import KFold
fold=KFold(n_splits=3)
# SO WHAT THE KFOLD FUNCTION DOES IS IT GOES THROUGH THE ARRAY OR THE DATASET AND INDEXES THE DATASET OR ARRAY
# AND UNIFORMLY JUMBLES INDEX WHICH WE CAN ASSIGN TO THE TRAINING AND TESTING SET SUCH THAT IT COVERS THE
# COMPLETE DATASET
# 
for train_index, test_index in fold.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [70]:
# LETS DEFINE A FUNCTION TO PERFORM TRAINING AND CHECKING THE SCORE OF THE MODEL 
# THIS FUNCTION WILL TAKE IN THE PARAMETERS MODEL, X_TRAIN, X_test,Y_train,Y_test AND TRAIN THE MODEL USING 
# X_TRAIN AND Y_TRAIN AND WILL RETURN THE SCORE OF THE MODEL USING X_TEST AND Y_TEST
def score_model(model,X_train,X_test,Y_train,Y_test):
    model.fit(X_train,Y_train)
    return model.score(X_test,Y_test)
print(score_model(LogisticRegression(),X_train,X_test,Y_train,Y_test))
print(score_model(SVC(),X_train,X_test,Y_train,Y_test))
print(score_model(RandomForestClassifier(),X_train,X_test,Y_train,Y_test))

C:\Users\Arjun VJ\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9527777777777777
0.9805555555555555
0.9722222222222222


In [78]:
# STRATIFIEDKFOLD - DOES A BETTER DISTRIBUTION OF FOLDS BY SPLITTING THEM UNIFORMLY AND IS VERY WELL SUITED FOR 
# DATASET WITH IMBALANCED DATA DISTRIBUTION
# SO IN OTHERWORDS STRATIFIEDKFOLD IS A BETTER VERSION OF KFOLD 
from sklearn.model_selection import StratifiedKFold
fold=StratifiedKFold(n_splits=3)
LogisticRegression_score=[]
SVM_score=[]
RandomForestClassifier_score=[]
# SO WE 
for training_index,testing_index in fold.split(digits.data,digits.target): 
    X_train, X_test, Y_train, Y_test = digits.data[training_index], digits.data[testing_index], \
                                        digits.target[train_index], digits.target[testing_index]
    # SO THE SCORE MODEL RETURNS THE SCORE OF THE MODEL WHICH IS THEN APPENDED TO EMPTY ARRAY DEFINED ABOVE
    LogisticRegression_score.append(score_model(LogisticRegression(),X_train,X_test,Y_train,Y_test))
    SVM_score.append(score_model(SVC(),X_train,X_test,Y_train,Y_test))
    RandomForestClassifier_score.append(score_model(RandomForestClassifier(),X_train,X_test,Y_train,Y_test))
print(LogisticRegression_score)

C:\Users\Arjun VJ\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Arjun VJ\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https:/

[0.11519198664440734, 0.7078464106844741, 0.9165275459098498]


In [85]:
# cross_validation_score() - THE ABOVE OPERATION OF PERFORMING KFOLD AND STARTIFIED KFOLD OPERATION ON THE DATASET ALONG WITH THE SCORE_MODEL 
# FUNCTION CAN BE PERFORMED BY THE CROSS_VALIDATION_SCORE FUNCTION
from sklearn.model_selection import cross_val_score
# JUST LIKE SCORE_MODEL WE DEFINED ABOVE ALL WE HAVE TO PASS IS THE MODEL(), digits.data, digits.target AS PARAMETER
print(cross_val_score(LogisticRegression(),digits.data,digits.target))
print(cross_val_score(SVC(),digits.data,digits.target))
print(cross_val_score(RandomForestClassifier(),digits.data,digits.target))

C:\Users\Arjun VJ\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Arjun VJ\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https:/

[0.92222222 0.86944444 0.94150418 0.93871866 0.89693593]
[0.96111111 0.94444444 0.98328691 0.98885794 0.93871866]
[0.925      0.91388889 0.95821727 0.96100279 0.91643454]


In [87]:
# WE CAN NOT ONLY USE THE CROSS VALIDATION SCORE FOR CHECKING PERFORMANCE OF DIFFERENT MODEL BUT ALSO 
# HOW EACH PARAMETER CHANGES THE PERFORMANCE OF THE MODEL 
# THIS IS CALLED PARAMETER FINE TUNING 
print(cross_val_score(RandomForestClassifier(n_estimators=150,criterion='entropy'),digits.data,digits.target))

[0.93333333 0.91388889 0.95543175 0.9637883  0.9275766 ]


In [ ]:
print(cross_val_score(RandomForestClassifier(n_estimators=50,criterion='gini'),digits.data,digits.target))