In [2]:
# RANDOM FOREST 
# RANDOM FOREST IS A COMBINATION OF DECISION TREES WHERE IN THE DECISION IS TAKEN BY VARIOUS DECISION TREES FOR THE
# SAME DATASET AND THE DECISION CHOSEN BY THE MAJORITY IS THE PREDICTED VALUE
# THE DATASETS ARE RANDOMLY SPLIT AND EACH OF THE DECISION TREE IS TRAINED DIFFERENT RANDOMLY SPLIT PORTIONS OF THE
# THE DATASETS HENCE THE WORD 'RANDOM'
# SINCE A LOT OF DECISION TREES ARE TRAINED AND USED FOR PREDICTION HENCE THE WORD 'FOREST'

In [4]:
import pandas as pd
import numpy as np 
from sklearn.datasets import load_digits

In [5]:
digits=load_digits()

In [6]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [10]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]], shape=(1797, 64))

In [12]:
len(digits.feature_names)

64

In [13]:
# THE TARGET LABELS ARE 0-9
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# THE TARGET IS 0-9 TILL FOR 1798 ROWS
digits.target

array([0, 1, 2, ..., 8, 9, 8], shape=(1797,))

In [27]:
df=pd.DataFrame(digits.data)
df

0    1     2     3     4     5    6    7    8    9   ...   54   55  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  4.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  1.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  8.0  0.0   

       56   57   58    59    60    61   62   63  
0     0.0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1     0.0  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2     0.0  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3     0.0  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4     0.0  0.0  0.0   2.0  16.0   4.0  0.0  0.0  
...   ...  ...  ...   ...   ...   ...  ...  ...  
1792  0.0  0.0  2.0  14.0  15.0   9.0  0.0  0.0  
1793  0.0  0.0  6.0  16.0  14.0   6.0  0.0  0.0  
1794  0.0  0.0  2.0   9.0  13.0   6.0  0.0  0.0  
1795  0.0  0.0  5.0  12.0  16.0  12.0  0.0  0.0  
1796  0.0  1.0  8.0  12.0  14.0  12.0  1.0  0.0  

[1797 rows x 64 columns]

In [29]:
# LETS APPEND THE TARGET COLUMN TO THE DATAFRAME 
df['Target']=pd.DataFrame(digits.target)
df

0    1     2     3     4     5    6    7    8    9  ...   55   56  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  0.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  0.0  0.0   

       57   58    59    60    61   62   63  Target  
0     0.0  6.0  13.0  10.0   0.0  0.0  0.0       0  
1     0.0  0.0  11.0  16.0  10.0  0.0  0.0       1  
2     0.0  0.0   3.0  11.0  16.0  9.0  0.0       2  
3     0.0  7.0  13.0  13.0   9.0  0.0  0.0       3  
4     0.0  0.0   2.0  16.0   4.0  0.0  0.0       4  
...   ...  ...   ...   ...   ...  ...  ...     ...  
1792  0.0  2.0  14.0  15.0   9.0  0.0  0.0       9  
1793  0.0  6.0  16.0  14.0   6.0  0.0  0.0       0  
1794  0.0  2.0   9.0  13.0   6.0  0.0  0.0       8  
1795  0.0  5.0  12.0  16.0  12.0  0.0  0.0       9  
1796  1.0  8.0  12.0  14.0  12.0  1.0  0.0       8  

[1797 rows x 65 columns]

In [32]:
# NOW LETS SPLIT THE DATASET INTO TRAINING AND TESTING SET USING TRAIN_TEST_SPLIT
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(df.drop('Target',axis='columns'),df.Target,test_size=0.2)

In [33]:
X_train

0    1     2     3     4     5    6    7    8    9   ...    54   55  \
1382  0.0  0.0   0.0  10.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  13.0  0.0   
254   0.0  0.0   3.0  12.0   5.0   0.0  0.0  0.0  0.0  1.0  ...   2.0  0.0   
1446  0.0  1.0  11.0  15.0  13.0   2.0  0.0  0.0  0.0  8.0  ...   7.0  0.0   
1094  0.0  0.0   0.0  13.0  13.0   0.0  0.0  0.0  0.0  0.0  ...  16.0  6.0   
1729  0.0  0.0   4.0  12.0  13.0   1.0  0.0  0.0  0.0  0.0  ...  11.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...   ...  ...   
1739  0.0  0.0  10.0  11.0   7.0   0.0  0.0  0.0  0.0  4.0  ...   1.0  0.0   
584   0.0  0.0   3.0  15.0   6.0   0.0  0.0  0.0  0.0  1.0  ...   0.0  0.0   
1672  0.0  0.0   9.0  15.0  16.0  15.0  2.0  0.0  0.0  4.0  ...   0.0  0.0   
157   0.0  0.0  10.0  16.0  14.0   1.0  0.0  0.0  0.0  0.0  ...   0.0  0.0   
57    0.0  0.0   0.0   1.0   9.0  11.0  0.0  0.0  0.0  0.0  ...   4.0  0.0   

       56   57    58    59    60    61    62   63  
1382  0.0  0.0   0.0   9.0  16.0  15.0   5.0  0.0  
254   0.0  0.0   2.0  13.0  14.0   7.0   0.0  0.0  
1446  0.0  1.0  15.0  16.0  15.0   8.0   1.0  0.0  
1094  0.0  0.0   1.0  13.0  16.0  16.0  15.0  1.0  
1729  0.0  0.0   5.0  16.0  14.0   8.0   0.0  0.0  
...   ...  ...   ...   ...   ...   ...   ...  ...  
1739  0.0  0.0   7.0  12.0   8.0   0.0   0.0  0.0  
584   0.0  0.0   5.0  15.0   4.0   0.0   0.0  0.0  
1672  0.0  0.0  11.0  12.0   7.0   1.0   0.0  0.0  
157   0.0  0.0  13.0   9.0   0.0   0.0   0.0  0.0  
57    0.0  0.0   0.0   0.0   9.0  13.0   3.0  0.0  

[1437 rows x 64 columns]

In [34]:
len(X_train)

1437

In [36]:
# THE RANDOM FOREST CLASSIFIER IS IN THE ENSEMBLE MODULE OF SKLEARN
# ENSEMBLE CONSISTS OF MACHINE LEARNING MODEL WITH MULTIPLE MODELS/ALGORITHMS 
# SINCE RANDOM FOREST IS JUST A COMBINATION OF DECISION TREES IT IS STORED IN ENSEMBLE OF SKLEARN
from sklearn.ensemble import RandomForestClassifier
# LETS CREATE AN OBJECT OF THE RANDOMFORESTCLASSIFIER
# THE CRITERION CAN EITHER BE 'gini' OR 'entropy' or 'log_loss' AND DECIDES THE WAY IN WHICH THE DECISION TREE IS 
# PLOTTED
# THE n_estimators CAN BE OF ANY NUMBER AND IT DECIDES THE NUMBER OF DECISION TREE IN THE RANDOM FOREST
model=RandomForestClassifier()
model.fit(X_train,Y_train)

RandomForestClassifier()

In [37]:
# NOW LETS CHECK THE SCORE/PERFORMANCE OF THE MODEL AND IT HAS SCORED AN ACCURACY OF 96% 
model.score(X_test,Y_test)

0.9694444444444444

In [40]:
from sklearn.ensemble import RandomForestClassifier 
model=RandomForestClassifier(criterion='entropy')
model.fit(X_train,Y_train)

RandomForestClassifier(criterion='entropy')

In [41]:
# SO WITH CRITERION AS 'entropy IT PERFORMANCE INCREASE TO 97 %
model.score(X_test,Y_test)

0.9722222222222222

In [42]:
# SO IT THE PERFORMANCE ROSE FROM 97.22% TO 97.77% WHEN WE CHANGED THE n_estimators from 100 TO 1000 AND CRITERION
# TO 'entropy'
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=1000,criterion='entropy')
model.fit(X_train,Y_train)

RandomForestClassifier(criterion='entropy', n_estimators=1000)

In [43]:
model.score(X_test,Y_test)

0.9777777777777777